version: "3"

name: MyBrilliantProject-dev

services:

  MyBrilliantProject-dev:
    env_file: .env
    restart: unless-stopped
    build:
      context: ".."
      dockerfile: "./docker-compose/Dockerfile.base"
    volumes:
    - ../src:/src
    - ../tests:/tests
    - /logs:/logs
    networks:
    - MyBrilliantProject-dev-network

networks:
  MyBrilliantProject-dev-network:
